# Enable logging
CONFIG_LOG=y
# Set default log level to INFO
CONFIG_LOG_DEFAULT_LEVEL=3

# Enable shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y

# Enable RGB LED strip
CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_DBG=y
